spring:
  cloud:
    config:
      enabled: false
  config:
    import-check:
      enabled: false
  activate:
    on-profile: dev
  profiles:
    active: dev
  logging:
    level:
      org:
        springframework: DEBUG
        hibernate: INFO
    file:
      name: logs/users-service.log
  datasource:
    url: jdbc:postgresql://ep-tiny-smoke-a5ru3nok.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_sZWfBql5Ne4H
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

name: users-service
server:
  port: 8081
  servlet:
    context-path: /users-service
  tomcat:
    access log:
      enabled: true
      directory: logs
      prefix: access_log.
      suffix: .log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: users-service
      description: Users Service
      version: 1.0.0

security:
  jwt:
    secret: f5a8074c32fecff1882b4f6384d407b5a8c2d418dad3832f7bd7f660ef137dc149a34fb0d1167532978e5e8f5d78424fc495af1cb33a2f831c0a6a4be72d67e1d90b76d322b53f129f7d5e8e62b521690cc815d0938871437c8d9d124295d336866b4501cc260452a7f8f6677b064f5d74f41fa0a00dfa7e6d1572ee4d63169b6f90a302934ecbb68eeb578453e212836df64ca07a61b336993b6eb182409daa8574354cb4dd00c32e81f44c089ace761c615807dd2d302696b840ebe48c547af0ae3c178d7b24895ecbcf1747bf6db2a4371ddbee53563f2f51bc4b8cc030b26be0c08cc0dcec03288634255807e99ab3140b5a3e0fef63d465fc11083448d8
    expiration: 86400000
    header: Authorization
    prefix: Bearer
    issuer: users-service
    audience: users-service