spring:
  cloud:
    config:
      enabled: false
  config:
    import-check:
      enabled: false
  activate:
    on-profile: dev
  profiles:
    active: dev
  logging:
    level:
      org:
        springframework: DEBUG
        hibernate: INFO
    file:
      name: logs/users-service.log
  datasource:
    url: jdbc:postgresql://ep-tiny-smoke-a5ru3nok.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_sZWfBql5Ne4H
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

name: users-service
server:
  port: 8081
  servlet:
    context-path: /users-service
  tomcat:
    access log:
      enabled: true
      directory: logs
      prefix: access_log.
      suffix: .log
